default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_home_inventory_tracker
  username: postgres
  password: ?Shanice123

test:
  <<: *default
  database: rails_home_inventory_tracker_test
  username: postgres
  password: ?Shanice123

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>